//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tom_For_Fabric.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tom_For_Fabric.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///
        ///Source = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;),
        ///dbo_DateDimension = Source{[Schema=&quot;Sales&quot;,Item=&quot;DateDimension&quot;]}[Data],
        ///#&quot;Select Columns&quot; = Table.SelectColumns( dbo_DateDimension,{&quot;Date&quot;,
        ///&quot;Year&quot;,
        ///&quot;Month_Number&quot;,
        ///&quot;Month_Name&quot;,
        ///&quot;Day&quot;,
        ///&quot;Weekday_Number&quot;,
        ///&quot;Weekday_Name&quot;,
        ///&quot;IsWeekend&quot;,
        ///&quot;Quarter&quot;,
        ///&quot;Quarter_Name&quot;,
        ///&quot;Year_Quarter&quot;,
        ///&quot;Week_Number&quot;,
        ///&quot;Year_Month&quot;,
        ///&quot;IsLeapYear&quot;})
        ///in
        ///#&quot;Select Columns&quot;
        ///    .
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///    SalesCustomer = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT CustomerID,AccountNumber FROM Sales.Customer&quot;]),  
        ///  
        ///    PersonPerson = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT BusinessEntityID,FirstName,LastName FROM Person.Person&quot;]),  
        ///  
        ///    JoinTables = Table.Join(SalesCustomer, &quot;CustomerID&quot;, PersonPerson, &quot;BusinessEntityID&quot;, JoinKind.Inner),
        ///    Result = Table.SelectColumns(JoinTables, {&quot;Cu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///    SalesOrderHeader = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT SalesOrderID SalesOrderId_H,CustomerID,SalesOrderNumber,PurchaseOrderNumber,OrderDate,DueDate,ShipDate,TerritoryID FROM Sales.SalesOrderHeader&quot;]),  
        ///  
        ///    SalesOrderDetails = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT SalesOrderID SalesOrderId_D,ProductID, OrderQty,CarrierTrackingNumber,OrderQty,UnitPrice,UnitPriceDiscount FROM Sales. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactSales {
            get {
                return ResourceManager.GetString("FactSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///    Product = Sql.Database(&quot;tcp:yourssqlserver,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT ProductID, ProductSubcategoryID PSC_ID_1, Name ProductName, ProductNumber FROM Production.Product&quot;]),  
        ///
        ///    ProductSubcategory = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;, [Query=&quot;SELECT ProductSubcategoryID PSC_ID_2, ProductCategoryID PC_ID_1, Name ProductSubCategoryName FROM Production.ProductSubcategory&quot;]),  
        ///
        ///    ProductCategory = Sql.Database(&quot;tcp:yourssqlserver.database. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///Source = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;),
        ///    dbo_ProductCategory = Source{[Schema=&quot;Production&quot;,Item=&quot;ProductCategory&quot;]}[Data],
        ///    #&quot;Select Columns&quot; = Table.SelectColumns(dbo_ProductCategory,{&quot;ProductCategoryID&quot;, &quot;Name&quot;})
        ///in
        ///    #&quot;Select Columns&quot;.
        /// </summary>
        internal static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///Source = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;),
        ///    dbo_ProductSubcategory = Source{[Schema=&quot;Production&quot;,Item=&quot;ProductSubcategory&quot;]}[Data],
        ///    #&quot;Select Columns&quot; = Table.SelectColumns(dbo_ProductSubcategory,{&quot;ProductSubcategoryID&quot;,&quot;ProductCategoryID&quot;, &quot;Name&quot;})
        ///in
        ///    #&quot;Select Columns&quot;.
        /// </summary>
        internal static string ProductSubCategory {
            get {
                return ResourceManager.GetString("ProductSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let
        ///Source = Sql.Database(&quot;tcp:yourssqlserver.database.windows.net,1433&quot;, &quot;AdventureWorks&quot;),
        ///    dbo_SalesTerritory = Source{[Schema=&quot;Sales&quot;,Item=&quot;SalesTerritory&quot;]}[Data],
        ///    #&quot;Select Columns&quot; = Table.SelectColumns( dbo_SalesTerritory,{&quot;TerritoryID&quot;,&quot;Name&quot;,&quot;ModifiedDate&quot;})
        ///in
        ///    #&quot;Select Columns&quot;.
        /// </summary>
        internal static string SalesTerritory {
            get {
                return ResourceManager.GetString("SalesTerritory", resourceCulture);
            }
        }
    }
}
